version: '3.8'

services:
  # The PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # The Spring Boot Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: url-shortener-app
    depends_on:
      - db # Wait for the db service to be ready before starting
    ports:
      - "8080:8080"
    environment:
      # These environment variables will override the application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url_shortener_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      # Ensure Hibernate uses the correct dialect and lets Flyway/Liquibase handle schema
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  # Define the named volume for data persistence
  postgres-data: